import streamlit as st
from streamlit_sortables import sort_items
from pages.tools.utils import custom_style

st.title("The Art of Persuasion: Evaluating the Impact of Ethos, Pathos, and Logos on Argument Effectiveness")

st.markdown("""
- **Student Researcher**: Sabrina Mazumder. For questions or concerns, please contact [dylansabrina@gmail.com](mailto:dylansabrina@gmail.com).

- **Purpose of Project**: The study is designed to address two questions:  
  - Among logos, ethos, and pathos, which rhetorical appeal is most effective in changing people’s minds when used by generative artificial intelligence?  
  - Does the persuasive impact of these appeals differ when the arguments are personalized?  

- **Participation Requirements**: Participants will be asked to share personal information, including gender, age, religion, political beliefs, open-mindedness, 
            personal values, and opinions.  

- **Time Commitment**: ~30 minutes

- **Risks**: Participation involves exposure to arguments generated by artificial intelligence, which may contain bias, emotionally charged language, or 
            factual inaccuracies. Some individuals may experience discomfort or psychological stress when engaging with such material. Limited personal data will be 
            collected to contextualize responses. Additionally, as with any online activity, there is a risk of data breach.  

- **Benefits**: No direct benefits to participants are expected. However, the survey questions may be found interesting, and the responses will contribute 
            to research on the persuasive capabilities of generative artificial intelligence.  

- **Confidentiality**: All survey data will be anonymized and used solely for research purposes. Findings will only be reported in aggregate form, ensuring 
            that no individual participant is identified.  

By checking the box below, you confirm that you understand the above information and give consent to participate in the survey.
""")

consent = st.checkbox("I consent")
if consent:
    if st.button("Next", type="primary"):
        st.switch_page("pages/Instructions.py")
